/* Everyday foods for Search: answers instantly and offline. Typical values per 100 g (or 100 ml),
 * mostly from USDA / McCance & Widdowson, cooked unless the name says otherwise.
 * Each row: [name, kcal per 100, typical serving, what one serving is called, unit ("g" unless "ml"), extra search words]
 * Meat, fish and grains come in cooked and raw versions: type "raw" or "dry" to get the uncooked weight.
 * Add your own rows at the bottom; keep the shape and push. */
const FOODS = [
  // --- poultry & meat
  ["Chicken breast, cooked, skinless", 165, 120, "breast", "g", "grilled roast"],
  ["Chicken thigh, cooked, skinless", 179, 80, "thigh", "g", "boneless"],
  ["Chicken thigh, cooked, with skin", 229, 90, "thigh", "g", "roast"],
  ["Chicken drumstick, cooked, with skin", 216, 70, "drumstick", "g", "leg"],
  ["Chicken wing, cooked, with skin", 290, 35, "wing", "g", "wings"],
  ["Roast chicken, meat and skin", 239, 150, "portion", "g", "rotisserie"],
  ["Turkey breast, cooked", 147, 120, "portion", "g", ""],
  ["Beef mince 5% fat, cooked", 170, 125, "portion", "g", "lean ground beef"],
  ["Beef mince 20% fat, cooked", 254, 125, "portion", "g", "ground beef"],
  ["Beef steak, grilled", 200, 200, "steak", "g", "sirloin rump ribeye"],
  ["Roast beef", 230, 120, "portion", "g", ""],
  ["Pork chop, grilled", 231, 150, "chop", "g", ""],
  ["Pork loin, roast, lean", 180, 120, "portion", "g", "roast pork"],
  ["Pulled pork", 220, 150, "portion", "g", ""],
  ["Bacon, streaky, grilled", 400, 25, "rasher", "g", "crispy"],
  ["Bacon, back, grilled", 287, 35, "rasher", "g", ""],
  ["Sausage, pork, grilled", 300, 55, "sausage", "g", "banger"],
  ["Ham, sliced", 110, 30, "slice", "g", "deli"],
  ["Lamb chop, grilled", 294, 100, "chop", "g", ""],
  ["Roast lamb, leg", 240, 120, "portion", "g", ""],
  ["Salami", 336, 10, "slice", "g", ""],
  ["Chorizo", 455, 30, "portion", "g", ""],
  ["Pepperoni", 500, 15, "portion", "g", ""],
  ["Black pudding, fried", 297, 60, "slice", "g", ""],
  // --- raw / uncooked weights (for when you weigh before cooking; no oil counted)
  ["Chicken breast, raw, skinless", 120, 150, "breast", "g", "uncooked"],
  ["Chicken thigh, raw, skinless", 121, 100, "thigh", "g", "uncooked boneless"],
  ["Chicken thigh, raw, with skin", 211, 110, "thigh", "g", "uncooked"],
  ["Chicken drumstick, raw, with skin", 161, 90, "drumstick", "g", "uncooked leg"],
  ["Chicken wing, raw, with skin", 191, 45, "wing", "g", "uncooked wings"],
  ["Whole chicken, raw", 215, 250, "portion", "g", "uncooked"],
  ["Turkey breast, raw", 114, 150, "portion", "g", "uncooked"],
  ["Turkey mince, raw", 150, 125, "portion", "g", "uncooked ground turkey"],
  ["Beef mince 5% fat, raw", 137, 125, "portion", "g", "uncooked lean ground beef"],
  ["Beef mince 20% fat, raw", 254, 125, "portion", "g", "uncooked ground beef"],
  ["Beef steak, raw", 170, 225, "steak", "g", "uncooked sirloin rump ribeye"],
  ["Pork chop, raw", 190, 175, "chop", "g", "uncooked"],
  ["Pork loin, raw, lean", 140, 150, "portion", "g", "uncooked"],
  ["Pork mince, raw", 260, 125, "portion", "g", "uncooked ground pork"],
  ["Sausage, pork, raw", 290, 65, "sausage", "g", "uncooked banger"],
  ["Bacon, streaky, raw", 300, 30, "rasher", "g", "uncooked"],
  ["Bacon, back, raw", 220, 40, "rasher", "g", "uncooked"],
  ["Lamb chop, raw", 280, 120, "chop", "g", "uncooked"],
  ["Lamb leg, raw", 200, 150, "portion", "g", "uncooked"],
  ["Lamb mince, raw", 280, 125, "portion", "g", "uncooked ground lamb"],
  ["Salmon fillet, raw", 200, 150, "fillet", "g", "uncooked"],
  ["Cod fillet, raw", 82, 150, "fillet", "g", "uncooked white fish"],
  ["Haddock, raw", 74, 150, "fillet", "g", "uncooked"],
  ["Tuna steak, raw", 109, 150, "steak", "g", "uncooked"],
  ["Prawns, raw", 85, 100, "portion", "g", "uncooked shrimp"],
  ["Mackerel, raw", 205, 120, "fillet", "g", "uncooked"],
  ["Egg, raw", 143, 50, "egg", "g", "uncooked eggs"],
  ["Rice, dry", 365, 75, "portion", "g", "uncooked basmati jasmine"],
  ["Pasta, dry", 371, 75, "portion", "g", "uncooked spaghetti penne fusilli"],
  ["Egg noodles, dry", 384, 65, "nest", "g", "uncooked"],
  ["Couscous, dry", 376, 60, "portion", "g", "uncooked"],
  ["Quinoa, dry", 368, 60, "portion", "g", "uncooked"],
  ["Lentils, dry", 353, 60, "portion", "g", "uncooked"],
  ["Potato, raw", 77, 175, "potato", "g", "uncooked"],
  ["Sweet potato, raw", 86, 150, "portion", "g", "uncooked"],
  // --- fish & seafood
  ["Salmon fillet, cooked", 208, 150, "fillet", "g", "baked grilled"],
  ["Smoked salmon", 117, 50, "portion", "g", "lox"],
  ["Tuna, tinned in water, drained", 116, 100, "tin", "g", "canned"],
  ["Tuna, tinned in oil, drained", 198, 100, "tin", "g", "canned"],
  ["Tuna steak, cooked", 132, 150, "steak", "g", ""],
  ["Cod fillet, cooked", 105, 150, "fillet", "g", "white fish"],
  ["Haddock, cooked", 116, 150, "fillet", "g", ""],
  ["Prawns, cooked", 99, 100, "portion", "g", "shrimp"],
  ["Fish fingers, grilled", 233, 28, "finger", "g", "fish sticks"],
  ["Battered fish, chip shop", 220, 200, "piece", "g", "fish and chips cod"],
  ["Mackerel, cooked", 262, 120, "fillet", "g", ""],
  ["Sardines, tinned in oil, drained", 208, 90, "tin", "g", "canned"],
  ["Calamari, fried", 175, 100, "portion", "g", "squid"],
  // --- eggs & dairy
  ["Egg, boiled", 155, 50, "egg", "g", "hard soft eggs"],
  ["Egg, fried", 196, 50, "egg", "g", "eggs"],
  ["Egg, scrambled", 149, 60, "egg", "g", "eggs"],
  ["Egg, poached", 143, 50, "egg", "g", "eggs"],
  ["Egg white", 52, 33, "white", "g", "eggs"],
  ["Egg yolk", 322, 17, "yolk", "g", "eggs"],
  ["Omelette, 2 egg, plain", 154, 120, "omelette", "g", "eggs"],
  ["Milk, whole", 64, 250, "glass", "ml", "full fat blue"],
  ["Milk, semi-skimmed", 47, 250, "glass", "ml", "green"],
  ["Milk, skimmed", 35, 250, "glass", "ml", "red"],
  ["Oat milk", 45, 250, "glass", "ml", "oatly"],
  ["Almond milk, unsweetened", 15, 250, "glass", "ml", ""],
  ["Cheddar cheese", 403, 30, "portion", "g", "cheese"],
  ["Mozzarella", 280, 30, "portion", "g", "cheese"],
  ["Feta", 264, 30, "portion", "g", "cheese"],
  ["Parmesan", 431, 10, "portion", "g", "cheese"],
  ["Brie", 334, 30, "portion", "g", "cheese"],
  ["Halloumi, grilled", 321, 80, "portion", "g", "cheese"],
  ["Cream cheese", 342, 30, "portion", "g", "philadelphia"],
  ["Cottage cheese", 98, 100, "portion", "g", ""],
  ["Greek yogurt, full fat", 97, 150, "pot", "g", "yoghurt"],
  ["Greek yogurt, 0% fat", 57, 150, "pot", "g", "yoghurt fage"],
  ["Natural yogurt", 61, 150, "pot", "g", "yoghurt plain"],
  ["Fruit yogurt", 90, 125, "pot", "g", "yoghurt flavoured"],
  ["Butter", 717, 10, "portion", "g", ""],
  ["Double cream", 449, 30, "portion", "ml", "heavy cream"],
  ["Single cream", 193, 30, "portion", "ml", ""],
  ["Ice cream, vanilla", 207, 75, "scoop", "g", ""],
  // --- bread, grains, potatoes
  ["Bread, white", 265, 36, "slice", "g", "toast"],
  ["Bread, wholemeal", 247, 36, "slice", "g", "brown toast wholewheat"],
  ["Sourdough", 289, 50, "slice", "g", "bread"],
  ["Bagel", 250, 90, "bagel", "g", ""],
  ["Pitta bread", 275, 60, "pitta", "g", ""],
  ["Naan bread", 290, 90, "naan", "g", ""],
  ["Tortilla wrap", 300, 60, "wrap", "g", ""],
  ["Croissant", 406, 60, "croissant", "g", ""],
  ["Bread roll", 280, 60, "roll", "g", "bun bap"],
  ["Burger bun", 280, 55, "bun", "g", "brioche"],
  ["Crumpet", 199, 40, "crumpet", "g", ""],
  ["English muffin", 227, 60, "muffin", "g", ""],
  ["Garlic bread", 350, 40, "slice", "g", ""],
  ["Rice, white, cooked", 130, 150, "portion", "g", "boiled basmati jasmine"],
  ["Rice, brown, cooked", 123, 150, "portion", "g", ""],
  ["Egg fried rice", 165, 300, "portion", "g", "chinese"],
  ["Pilau rice", 150, 200, "portion", "g", "indian"],
  ["Pasta, cooked", 158, 180, "portion", "g", "spaghetti penne fusilli"],
  ["Egg noodles, cooked", 138, 200, "portion", "g", ""],
  ["Instant noodles, dry", 450, 85, "pack", "g", "ramen pot noodle"],
  ["Couscous, cooked", 112, 150, "portion", "g", ""],
  ["Quinoa, cooked", 120, 150, "portion", "g", ""],
  ["Porridge oats, dry", 379, 40, "portion", "g", "oatmeal"],
  ["Porridge, made with milk", 110, 250, "bowl", "g", "oatmeal"],
  ["Cornflakes", 357, 30, "bowl", "g", "cereal"],
  ["Weetabix", 362, 19, "biscuit", "g", "cereal"],
  ["Granola", 450, 45, "bowl", "g", "cereal"],
  ["Muesli", 360, 45, "bowl", "g", "cereal"],
  ["Cheerios", 380, 30, "bowl", "g", "cereal"],
  ["Potato, boiled", 87, 150, "portion", "g", "new potatoes"],
  ["Jacket potato", 93, 200, "potato", "g", "baked"],
  ["Mashed potato", 113, 150, "portion", "g", "mash"],
  ["Roast potatoes", 149, 100, "portion", "g", "roasties"],
  ["Chips, chip shop", 240, 200, "portion", "g", "fries"],
  ["Oven chips", 180, 150, "portion", "g", "fries"],
  ["French fries, fast food", 312, 114, "medium", "g", "mcdonalds"],
  ["Sweet potato, baked", 90, 150, "portion", "g", ""],
  ["Hash brown", 230, 55, "hash brown", "g", ""],
  ["Crisps", 530, 30, "bag", "g", "chips walkers"],
  ["Tortilla chips", 500, 40, "portion", "g", "doritos nachos"],
  ["Popcorn, salted", 500, 30, "portion", "g", ""],
  ["Popcorn, sweet", 430, 30, "portion", "g", "toffee"],
  ["Pretzels", 380, 30, "portion", "g", ""],
  // --- fruit
  ["Apple", 52, 180, "apple", "g", ""],
  ["Banana", 89, 118, "banana", "g", ""],
  ["Orange", 47, 130, "orange", "g", ""],
  ["Grapes", 69, 100, "handful", "g", ""],
  ["Strawberries", 32, 100, "portion", "g", ""],
  ["Blueberries", 57, 100, "portion", "g", ""],
  ["Raspberries", 52, 100, "portion", "g", ""],
  ["Pear", 57, 180, "pear", "g", ""],
  ["Peach", 39, 150, "peach", "g", "nectarine"],
  ["Watermelon", 30, 280, "slice", "g", ""],
  ["Melon", 34, 150, "portion", "g", "cantaloupe honeydew"],
  ["Pineapple", 50, 100, "portion", "g", ""],
  ["Mango", 60, 200, "mango", "g", ""],
  ["Kiwi", 61, 75, "kiwi", "g", ""],
  ["Avocado", 160, 70, "half", "g", ""],
  ["Cherries", 63, 100, "handful", "g", ""],
  ["Plum", 46, 66, "plum", "g", ""],
  ["Dates, Medjool", 277, 24, "date", "g", ""],
  ["Raisins", 299, 30, "handful", "g", "sultanas"],
  ["Clementine", 47, 75, "clementine", "g", "satsuma mandarin tangerine"],
  // --- vegetables & pulses
  ["Broccoli, cooked", 35, 90, "portion", "g", ""],
  ["Carrot", 41, 60, "carrot", "g", "carrots"],
  ["Peas, cooked", 81, 80, "portion", "g", ""],
  ["Sweetcorn", 96, 80, "portion", "g", "corn"],
  ["Corn on the cob", 96, 90, "cob", "g", ""],
  ["Spinach", 23, 80, "portion", "g", ""],
  ["Lettuce", 15, 50, "portion", "g", "salad leaves"],
  ["Tomato", 18, 120, "tomato", "g", ""],
  ["Cucumber", 15, 50, "portion", "g", ""],
  ["Onion", 40, 110, "onion", "g", ""],
  ["Pepper, bell", 26, 120, "pepper", "g", "capsicum"],
  ["Mushrooms", 22, 80, "portion", "g", ""],
  ["Courgette", 17, 100, "portion", "g", "zucchini"],
  ["Cauliflower, cooked", 25, 90, "portion", "g", ""],
  ["Green beans", 31, 80, "portion", "g", ""],
  ["Cabbage", 25, 80, "portion", "g", ""],
  ["Baked beans, tinned", 80, 210, "half tin", "g", "heinz"],
  ["Kidney beans, tinned", 127, 100, "portion", "g", ""],
  ["Chickpeas, tinned", 164, 100, "portion", "g", ""],
  ["Lentils, cooked", 116, 150, "portion", "g", ""],
  ["Hummus", 166, 30, "portion", "g", "houmous"],
  ["Olives", 115, 15, "portion", "g", ""],
  ["Tofu", 76, 100, "portion", "g", ""],
  ["Falafel", 333, 17, "falafel", "g", ""],
  ["Quorn mince", 105, 100, "portion", "g", "meat free"],
  // --- nuts, seeds, spreads
  ["Almonds", 579, 30, "handful", "g", "nuts"],
  ["Peanuts", 567, 30, "handful", "g", "nuts"],
  ["Cashews", 553, 30, "handful", "g", "nuts"],
  ["Walnuts", 654, 30, "handful", "g", "nuts"],
  ["Pistachios", 560, 30, "handful", "g", "nuts"],
  ["Mixed nuts", 607, 30, "handful", "g", ""],
  ["Peanut butter", 588, 20, "tablespoon", "g", ""],
  ["Chia seeds", 486, 15, "tablespoon", "g", ""],
  ["Whey protein powder", 380, 30, "scoop", "g", "protein shake"],
  // --- baking & cooking staples (so pasted recipes match)
  ["Flour, plain", 364, 100, "portion", "g", "all purpose white wheat"],
  ["Flour, self-raising", 350, 100, "portion", "g", "self rising"],
  ["Flour, wholemeal", 340, 100, "portion", "g", "wholewheat"],
  ["Cornflour", 381, 10, "tablespoon", "g", "cornstarch"],
  ["Breadcrumbs", 350, 30, "portion", "g", "panko"],
  ["Sugar, brown", 380, 4, "teaspoon", "g", "soft light dark muscovado demerara"],
  ["Icing sugar", 389, 30, "portion", "g", "powdered confectioners"],
  ["Cocoa powder", 228, 10, "tablespoon", "g", ""],
  ["Chocolate chips", 480, 30, "portion", "g", ""],
  ["Ground almonds", 579, 30, "portion", "g", "almond flour"],
  ["Desiccated coconut", 660, 20, "portion", "g", ""],
  ["Baking powder", 53, 4, "teaspoon", "g", ""],
  ["Bicarbonate of soda", 0.1, 4, "teaspoon", "g", "baking soda"],
  ["Salt", 0.1, 5, "teaspoon", "g", ""],
  ["Vanilla extract", 288, 4, "teaspoon", "ml", "essence"],
  ["Yeast, dried", 325, 7, "sachet", "g", ""],
  ["Spices, ground", 300, 2, "teaspoon", "g", "cinnamon paprika cumin curry powder chilli powder turmeric nutmeg ginger coriander garam masala pepper mixed spice"],
  ["Herbs, dried", 250, 1, "teaspoon", "g", "oregano thyme basil rosemary mixed herbs parsley"],
  ["Garlic", 149, 3, "clove", "g", ""],
  ["Ginger, fresh", 80, 10, "portion", "g", "root"],
  ["Chilli, fresh", 40, 15, "chilli", "g", "chili"],
  ["Lemon", 29, 60, "lemon", "g", "zest juice"],
  ["Lime", 30, 45, "lime", "g", "zest juice"],
  ["Spring onion", 32, 15, "onion", "g", "scallion"],
  ["Celery", 16, 40, "stick", "g", ""],
  ["Leek", 61, 90, "leek", "g", ""],
  ["Aubergine", 25, 250, "aubergine", "g", "eggplant"],
  ["Kale", 49, 70, "portion", "g", ""],
  ["Stock cube", 250, 10, "cube", "g", "oxo knorr"],
  ["Stock, made up", 5, 250, "portion", "ml", "broth"],
  ["Tinned tomatoes", 32, 200, "half tin", "g", "chopped canned"],
  ["Passata", 35, 100, "portion", "g", ""],
  ["Tomato puree", 82, 15, "tablespoon", "g", "paste purée"],
  ["Coconut milk, tinned", 230, 100, "portion", "ml", "canned"],
  ["Curry paste", 250, 30, "tablespoon", "g", "thai"],
  ["Sesame oil", 884, 5, "teaspoon", "g", ""],
  ["Coconut oil", 892, 14, "tablespoon", "g", ""],
  ["Sour cream", 198, 30, "tablespoon", "g", "soured"],
  ["Creme fraiche", 292, 30, "tablespoon", "g", "crème fraîche"],
  ["Mascarpone", 429, 50, "portion", "g", ""],
  ["Ricotta", 174, 50, "portion", "g", ""],
  ["Condensed milk", 321, 30, "tablespoon", "g", "sweetened"],
  ["Evaporated milk", 134, 30, "tablespoon", "ml", ""],
  ["Custard", 100, 150, "portion", "g", ""],
  ["Puff pastry", 380, 100, "portion", "g", "ready rolled"],
  ["Shortcrust pastry", 450, 100, "portion", "g", ""],
  ["Filo pastry", 300, 45, "sheet", "g", ""],
  // --- fats, sauces, condiments
  ["Olive oil", 884, 14, "tablespoon", "g", "oil"],
  ["Vegetable oil", 884, 14, "tablespoon", "g", "sunflower rapeseed oil"],
  ["Mayonnaise", 680, 15, "tablespoon", "g", "mayo hellmanns"],
  ["Light mayonnaise", 300, 15, "tablespoon", "g", "mayo"],
  ["Tomato ketchup", 112, 15, "tablespoon", "g", ""],
  ["BBQ sauce", 165, 20, "tablespoon", "g", "barbecue"],
  ["Soy sauce", 53, 15, "tablespoon", "ml", ""],
  ["Sweet chilli sauce", 220, 20, "tablespoon", "g", ""],
  ["Salad dressing, ranch", 430, 30, "portion", "g", "caesar"],
  ["Gravy", 40, 100, "portion", "ml", ""],
  ["Honey", 304, 21, "tablespoon", "g", ""],
  ["Jam", 250, 20, "tablespoon", "g", "marmalade"],
  ["Nutella", 539, 15, "tablespoon", "g", "chocolate spread"],
  ["Sugar", 387, 4, "teaspoon", "g", "caster granulated white"],
  ["Maple syrup", 260, 20, "tablespoon", "g", "golden syrup"],
  // --- sweets, cakes, snacks
  ["Milk chocolate", 535, 45, "bar", "g", "dairy milk galaxy"],
  ["Dark chocolate", 546, 30, "portion", "g", ""],
  ["Chocolate chip cookie", 488, 30, "cookie", "g", "biscuit"],
  ["Digestive biscuit", 480, 15, "biscuit", "g", ""],
  ["Chocolate digestive", 495, 17, "biscuit", "g", ""],
  ["Custard cream", 490, 12, "biscuit", "g", "bourbon"],
  ["Jaffa cake", 370, 12, "cake", "g", ""],
  ["Brownie", 466, 60, "brownie", "g", ""],
  ["Doughnut, glazed", 452, 60, "doughnut", "g", "donut krispy kreme"],
  ["Blueberry muffin", 377, 110, "muffin", "g", "cake"],
  ["Sponge cake with icing", 400, 80, "slice", "g", "birthday cake victoria"],
  ["Cheesecake", 321, 100, "slice", "g", ""],
  ["Apple pie", 265, 125, "slice", "g", ""],
  ["Flapjack", 460, 80, "flapjack", "g", ""],
  ["Gummy sweets", 343, 30, "handful", "g", "haribo jelly"],
  ["Cereal bar", 400, 30, "bar", "g", "granola bar"],
  ["Protein bar", 380, 60, "bar", "g", ""],
  ["Marshmallows", 318, 30, "handful", "g", ""],
  ["Ice lolly", 90, 70, "lolly", "g", "popsicle"],
  ["Choc ice bar", 300, 90, "bar", "g", "magnum ice cream"],
  ["Pancake, American", 227, 40, "pancake", "g", ""],
  ["Waffle", 290, 75, "waffle", "g", ""],
  ["Scone", 360, 60, "scone", "g", ""],
  // --- soft drinks & hot drinks (per 100 ml)
  ["Coca-Cola", 42, 330, "can", "ml", "coke pepsi cola"],
  ["Coke Zero / Diet Coke", 0.3, 330, "can", "ml", "pepsi max diet cola"],
  ["Lemonade", 40, 330, "can", "ml", "sprite 7up"],
  ["Orange juice", 45, 250, "glass", "ml", "oj"],
  ["Apple juice", 46, 250, "glass", "ml", ""],
  ["Energy drink", 45, 250, "can", "ml", "red bull monster"],
  ["Energy drink, sugar free", 1, 250, "can", "ml", "red bull monster"],
  ["Squash, diluted", 10, 250, "glass", "ml", "cordial robinsons"],
  ["Coffee, black", 1, 250, "cup", "ml", "americano espresso"],
  ["Latte, whole milk", 50, 300, "cup", "ml", "coffee flat white"],
  ["Cappuccino", 40, 300, "cup", "ml", "coffee"],
  ["Tea with milk", 8, 250, "cup", "ml", ""],
  ["Hot chocolate", 80, 250, "cup", "ml", "cocoa"],
  ["Milkshake", 110, 400, "milkshake", "ml", ""],
  ["Smoothie", 60, 250, "glass", "ml", ""],
  // --- alcohol (per 100 ml)
  ["Lager, 4.5%", 43, 568, "pint", "ml", "beer stella carling peroni"],
  ["Lager, 5%", 45, 330, "bottle", "ml", "beer corona"],
  ["Light beer", 30, 330, "bottle", "ml", ""],
  ["Cider", 45, 568, "pint", "ml", "strongbow thatchers"],
  ["Red wine", 85, 175, "glass", "ml", "wine"],
  ["White wine", 82, 175, "glass", "ml", "wine"],
  ["Rose wine", 83, 175, "glass", "ml", "wine rosé"],
  ["Prosecco", 76, 125, "glass", "ml", "champagne sparkling"],
  ["Vodka, 40%", 222, 25, "shot", "ml", "spirit"],
  ["Gin, 40%", 222, 25, "shot", "ml", "spirit"],
  ["Whisky, 40%", 222, 25, "shot", "ml", "whiskey bourbon jack daniels spirit"],
  ["Rum, 40%", 222, 25, "shot", "ml", "spirit"],
  ["Tequila", 231, 25, "shot", "ml", ""],
  ["Baileys", 327, 50, "measure", "ml", "liqueur"],
  ["Gin and tonic", 60, 175, "drink", "ml", "g&t"],
  ["Gin and slimline tonic", 31, 175, "drink", "ml", "g&t diet"],
  ["Vodka and Coke Zero", 28, 200, "drink", "ml", "diet"],
  ["Vodka soda", 28, 200, "drink", "ml", "lime"],
  ["Rum and Coke", 67, 175, "drink", "ml", ""],
  ["Aperol spritz", 65, 200, "drink", "ml", ""],
  ["Margarita", 120, 200, "drink", "ml", "cocktail"],
  ["Mojito", 88, 250, "drink", "ml", "cocktail"],
  ["Espresso martini", 130, 150, "drink", "ml", "cocktail"],
  ["Pina colada", 120, 200, "drink", "ml", "cocktail"],
  // --- takeaway & meals
  ["Cheeseburger, fast food", 250, 120, "burger", "g", "mcdonalds"],
  ["Big Mac", 257, 219, "burger", "g", "mcdonalds"],
  ["Quarter Pounder with cheese", 244, 210, "burger", "g", "mcdonalds"],
  ["Chicken nuggets", 290, 17, "nugget", "g", "mcnuggets"],
  ["Fried chicken, piece", 240, 100, "piece", "g", "kfc"],
  ["Hot dog", 290, 100, "hot dog", "g", ""],
  ["Pizza, margherita", 266, 100, "slice", "g", "cheese tomato"],
  ["Pizza, pepperoni", 290, 110, "slice", "g", "dominos"],
  ["Doner kebab", 250, 350, "kebab", "g", "takeaway"],
  ["Chicken shish kebab", 150, 300, "kebab", "g", "takeaway"],
  ["Chicken tikka masala", 150, 350, "portion", "g", "curry indian"],
  ["Chicken korma", 190, 350, "portion", "g", "curry indian"],
  ["Poppadom", 370, 12, "poppadom", "g", "indian"],
  ["Samosa", 260, 60, "samosa", "g", "indian"],
  ["Onion bhaji", 250, 50, "bhaji", "g", "indian"],
  ["Chow mein", 130, 350, "portion", "g", "chinese noodles"],
  ["Sweet and sour chicken", 150, 300, "portion", "g", "chinese"],
  ["Spring roll", 240, 60, "roll", "g", "chinese"],
  ["Sushi, nigiri", 145, 40, "piece", "g", "japanese"],
  ["Sushi, California roll", 130, 30, "piece", "g", "japanese maki"],
  ["Burrito", 200, 400, "burrito", "g", "mexican"],
  ["Taco", 220, 100, "taco", "g", "mexican"],
  ["Lasagne", 140, 400, "portion", "g", ""],
  ["Spaghetti bolognese", 130, 400, "portion", "g", "bolognaise"],
  ["Macaroni cheese", 170, 300, "portion", "g", "mac and cheese"],
  ["Shepherd's pie", 110, 400, "portion", "g", "cottage pie"],
  ["Chicken pie", 260, 250, "pie", "g", ""],
  ["Sausage roll", 350, 65, "roll", "g", "greggs"],
  ["Pork pie", 375, 140, "pie", "g", ""],
  ["Cornish pasty", 290, 250, "pasty", "g", "greggs"],
  ["Scotch egg", 250, 120, "egg", "g", ""],
  ["Quiche", 260, 120, "slice", "g", ""],
  ["Ham and cheese sandwich", 250, 180, "sandwich", "g", ""],
  ["BLT sandwich", 260, 200, "sandwich", "g", "bacon"],
  ["Cheese toastie", 330, 130, "toastie", "g", "grilled cheese"],
  ["Jacket potato with beans and cheese", 130, 400, "potato", "g", "baked"],
  ["Full English breakfast", 200, 450, "plate", "g", "fry up"],
  ["French toast", 230, 65, "slice", "g", "eggy bread"],
  ["Fish and chips, portion", 230, 400, "portion", "g", "chip shop"],
  ["Sunday roast dinner", 140, 500, "plate", "g", "roast"],
  ["Chicken caesar salad", 130, 300, "bowl", "g", ""],
  ["Soup, tomato", 55, 300, "bowl", "ml", "heinz"],
  ["Soup, chicken noodle", 40, 300, "bowl", "ml", ""]
];
